port: 7880

rtc:
  use_external_ip: false
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  packet_buffer_size_audio: 200
  # interfaces:
  #   includes:
  #     - en0
  #   excludes:
  #     - docker0
  # # ip address filter. If the machine has more than one ip address and you'd like it to use or skip specific ips,
  # # both inclusion and exclusion CIDR filters can be used together. If neither is defined (default), all ip on the machine will be used.
  # # If both of them are set, then only include takes effect.
  # ips:
  #   includes:
  #     - 10.0.0.0/16
  #   excludes:
  #     - 10.10.10.0/16

logging:
  level: info

room:
  enabled_codecs:
    - mime: audio/opus
    - mime: audio/red
    - mime: video/vp8
    - mime: video/vp9
    - mime: video/h264
    - mime: video/av1

audio:
  active_level: 40
  active_red_encoding: true
